#!/bin/sh

# Set these paths appropriately

BIN=/home/pacheco15/AuthorIdentification/src/pos_tagger/bin
CMD=/home/pacheco15/AuthorIdentification/src/pos_tagger/cmd
LIB=/home/pacheco15/AuthorIdentification/src/pos_tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
