#!/bin/sh

# Set these paths appropriately

BIN=/home/pacheco15/AuthorIdentification/src/pos_tagger/bin
CMD=/home/pacheco15/AuthorIdentification/src/pos_tagger/cmd
LIB=/home/pacheco15/AuthorIdentification/src/pos_tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
