#!/bin/sh

# Set these paths appropriately

BIN=/home/pacheco15/AuthorIdentification/src/pos_tagger/bin
CMD=/home/pacheco15/AuthorIdentification/src/pos_tagger/cmd
LIB=/home/pacheco15/AuthorIdentification/src/pos_tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
